# Import Libraries

In [1]:
import time
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras

2023-06-23 18:33:18.109539: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-23 18:33:18.164177: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-23 18:33:18.165156: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-23 18:33:19.169017: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


# TensorFlow basics

## Constants

### Scalar

In [2]:
t1 = tf.constant(7)
t1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
t1.shape, t1.ndim

(TensorShape([]), 0)

### Vector

In [4]:
t2 = tf.constant([1, 2])

In [5]:
t2.shape, t2.ndim

(TensorShape([2]), 1)

### Matrix

In [6]:
t3 = tf.constant([
    [10, 7],
    [7, 10]
])

In [7]:
t3.shape, t3.ndim

(TensorShape([2, 2]), 2)

### Tensor

In [8]:
t4 = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [9, 8, 7],
        [6, 5, 4]
    ],
    [
        [9, 8, 7],
        [6, 5, 4]
    ]
])

In [9]:
t4.shape, t4.ndim

(TensorShape([3, 2, 3]), 3)

### Summary

- Scalar - is a single number
- Vector - is a number with direction
- Matrix - is a 2D array of numnbers
- Tensor - is a n-dimensional array of numbers (where n is >= 0)

## Variable

In [10]:
v1 = tf.Variable(10)
v1, v1.shape

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>, TensorShape([]))

In [11]:
v2 = tf.Variable([10, 7])
v2, v2.shape

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 TensorShape([2]))

In [12]:
t2, v2

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

### Updating Value in Constant vs Variable

In [13]:
t2[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [14]:
v2[0].assign(7)
v2

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## Random

### Set seed for reproducibility

In [15]:
r1 = tf.random.Generator.from_seed(42)
r1

### Normal Distribution

In [16]:
r1 = r1.normal(shape=(3,2))
r1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### Uniform Distribution

In [17]:
tf.random.uniform((3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.97221875, 0.96958077],
       [0.7443274 , 0.65274394],
       [0.38763416, 0.19084394]], dtype=float32)>

### Random Seed

In [18]:
print(tf.random.uniform([1]))

tf.Tensor([0.53863907], shape=(1,), dtype=float32)


In [19]:
tf.random.set_seed(42)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [20]:
print(tf.random.uniform([1], seed=42))

tf.Tensor([0.4163028], shape=(1,), dtype=float32)


In [21]:
tf.random.set_seed(42)
print(tf.random.uniform([1], seed=42))
print(tf.random.uniform([1], seed=42))

tf.Tensor([0.4163028], shape=(1,), dtype=float32)
tf.Tensor([0.0332247], shape=(1,), dtype=float32)


### Shuffle

In [22]:
tf.random.shuffle([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

In [23]:
tf.random.set_seed(42) # Global Level Seed
tf.random.shuffle([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], seed=42) # Operation Level Seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

## Tensors & NumPy

In [24]:
tf.ones((10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.zeros(shape=(2, 2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

### NumPy to Tensors

In [26]:
tf.constant(
    np.arange(1, 25)
)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [27]:
tf.constant(
    np.arange(25),
    shape=(5, 5)
)

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])>

### Tensors to Numpy

In [28]:
t4.numpy()

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]],

       [[9, 8, 7],
        [6, 5, 4]]], dtype=int32)

## Atrributes of Tensors

In [29]:
t4

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]],

       [[9, 8, 7],
        [6, 5, 4]]], dtype=int32)>

### Shape

In [30]:
t4.shape

TensorShape([3, 2, 3])

### Rank / Dimension

In [31]:
t4.ndim

3

### Access or dimension

In [32]:
t4[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### Size

In [33]:
tf.size(t4)

<tf.Tensor: shape=(), dtype=int32, numpy=18>

### Data Type & Cast

In [34]:
t4.dtype

tf.int32

In [35]:
tf.cast(t4, dtype=tf.float16)

<tf.Tensor: shape=(3, 2, 3), dtype=float16, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[9., 8., 7.],
        [6., 5., 4.]],

       [[9., 8., 7.],
        [6., 5., 4.]]], dtype=float16)>

## Expanding Dimensions

In [36]:
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [37]:
t3.shape, t3.ndim

(TensorShape([2, 2]), 2)

In [38]:
t3[..., tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [39]:
tf.expand_dims(t3, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 7],
        [10]]], dtype=int32)>

In [40]:
tf.expand_dims(t3, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 7, 10]]], dtype=int32)>

In [41]:
tf.expand_dims(tf.expand_dims(t3, axis=0), axis=2)

<tf.Tensor: shape=(1, 2, 1, 2), dtype=int32, numpy=
array([[[[10,  7]],

        [[ 7, 10]]]], dtype=int32)>

## Manipulating Tensors

### Basic Arithematic Operations

In [42]:
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [43]:
t3 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [17, 20]], dtype=int32)>

###### Note: Underlying Tensor doesn't change

In [44]:
t3 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-3,  0]], dtype=int32)>

In [45]:
tf.multiply(t3, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [21, 30]], dtype=int32)>

In [46]:
tf.divide(t3, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [3.5, 5. ]])>

###### Nore: Arithematic operations can be done using (+ - / *) operators. But it is better to use tensorflow functions because it helps in performing the computations in GPU 

In [47]:
np.random.uniform(5), tf.math.sin(np.random.uniform(5))

(4.99490753471747, <tf.Tensor: shape=(), dtype=float32, numpy=-0.97098446>)

### Matrix Multiplication

#### Element-wise Multiplication

In [48]:
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [49]:
t3 * t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 49, 100]], dtype=int32)>

#### Matrix Multiplication

In [50]:
tf.linalg.matmul(t3, t3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149, 140],
       [140, 149]], dtype=int32)>

In [51]:
t3 @ t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[149, 140],
       [140, 149]], dtype=int32)>

#### Transpose

In [52]:
tf.transpose(t3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [53]:
tf.transpose([
    [1, 2],
    [3, 4],
    [5, 6]
])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

## Aggregation

In [54]:
t4

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]],

       [[9, 8, 7],
        [6, 5, 4]]], dtype=int32)>

### Min/Max/Mean/Sum

In [55]:
tf.reduce_min(t4)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [56]:
tf.reduce_max(t4)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [57]:
tf.reduce_mean(t4), tf.reduce_sum(t4)

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=99>)

In [58]:
tf.math.reduce_std(tf.cast(t4, dtype=tf.dtypes.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.2173557>

## Positional Min & Max

In [59]:
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [60]:
tf.argmax(t3)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>

In [61]:
tf.argmax(t3, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>

## Squeezing a tensor

In [62]:
tf.squeeze(t4)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]],

       [[9, 8, 7],
        [6, 5, 4]]], dtype=int32)>

In [63]:
tf.random.set_seed(42)

print(tf.constant(tf.random.uniform((1, 1, 3, 1), seed=42) ))
tf.random.set_seed(42)
tf.squeeze(
    tf.constant(tf.random.uniform((1, 1, 3, 1), seed=42))
)

tf.Tensor(
[[[[0.4163028 ]
   [0.26858163]
   [0.47968316]]]], shape=(1, 1, 3, 1), dtype=float32)


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.4163028 , 0.26858163, 0.47968316], dtype=float32)>

## One-Hot Encoding

In [64]:
tf.one_hot([0, 1, 2, 3], depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [65]:
tf.one_hot([0, 1, 2, 3], depth=3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

### Custom values in OHE

In [66]:
tf.one_hot([0, 1, 2, 3], depth=3, off_value='Switch Off', on_value='Switch On')

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'Switch On', b'Switch Off', b'Switch Off'],
       [b'Switch Off', b'Switch On', b'Switch Off'],
       [b'Switch Off', b'Switch Off', b'Switch On'],
       [b'Switch Off', b'Switch Off', b'Switch Off']], dtype=object)>

## Math

In [67]:
t4

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]],

       [[9, 8, 7],
        [6, 5, 4]]], dtype=int32)>

In [68]:
tf.math.sqrt(tf.cast(t4, dtype=tf.dtypes.float32))

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1.       , 1.4142135, 1.7320508],
        [2.       , 2.236068 , 2.4494898]],

       [[3.       , 2.828427 , 2.6457512],
        [2.4494898, 2.236068 , 2.       ]],

       [[3.       , 2.828427 , 2.6457512],
        [2.4494898, 2.236068 , 2.       ]]], dtype=float32)>

In [69]:
tf.math.log(tf.cast(t4, dtype=tf.dtypes.float64))

<tf.Tensor: shape=(3, 2, 3), dtype=float64, numpy=
array([[[0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947]],

       [[2.19722458, 2.07944154, 1.94591015],
        [1.79175947, 1.60943791, 1.38629436]],

       [[2.19722458, 2.07944154, 1.94591015],
        [1.79175947, 1.60943791, 1.38629436]]])>

## GPU

In [71]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]